version: "3.7"
services:
  # Database
  db:
    image: mariadb
    container_name: lemonade_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 3307:3306
    networks:
      - lemonade


  #Web server
  nginx:
    image: nginx:1.17-alpine
    container_name: lemonade_nginx
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
      - "5000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - lemonade

  # App
  app:
    build:
      args:
        user: maxwell
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lemonade-image
    container_name: lemonade_app
    depends_on:
      - nginx
      - db

    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lemonade

networks:
  lemonade:
    driver: bridge
